#include "src/game/envfx_snow.h"

const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Head__Capless__Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, charity_Head__Capless__Switch_Option_Head__Capless__mesh_layer_1_mat_override_c_face1_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Head__Capless__Switch_Option_Head__Capless__mesh_layer_4_mat_override_c_face1_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Head__Capless__Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, charity_Head__Capless__Switch_Option_Head__Capless__mesh_layer_1_mat_override_c_face2_2),
		GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Head__Capless__Switch_Option_Head__Capless__mesh_layer_4_mat_override_c_face2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Head__Capless__Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, charity_Head__Capless__Switch_Option_Head__Capless__mesh_layer_1_mat_override_c_face0_3),
		GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Head__Capless__Switch_Option_Head__Capless__mesh_layer_4_mat_override_c_face0_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Head__Capless__Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, charity_Head__Capless__Switch_Option_Head__Capless__mesh_layer_1_mat_override_c_face0_3),
		GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Head__Capless__Switch_Option_Head__Capless__mesh_layer_4_mat_override_c_face0_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Head__Capless__Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, charity_Head__Capless__Switch_Option_Head__Capless__mesh_layer_1_mat_override_c_face0_3),
		GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Head__Capless__Switch_Option_Head__Capless__mesh_layer_4_mat_override_c_face0_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Head__Capless__Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, charity_Head__Capless__Switch_Option_Head__Capless__mesh_layer_1_mat_override_c_face0_3),
		GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Head__Capless__Switch_Option_Head__Capless__mesh_layer_4_mat_override_c_face0_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Head__Capless__Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, charity_Head__Capless__Switch_Option_Head__Capless__mesh_layer_1_mat_override_c_face3_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Head__Capless__Switch_Option_Head__Capless__mesh_layer_4_mat_override_c_face3_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_Armature___Head__Capless_[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, charity_Head__Capless__Switch_Option_Head__Capless__mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Head__Capless__Switch_Option_Head__Capless__mesh_layer_4),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Head__Capless__Switch_opt1),
			GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Head__Capless__Switch_opt2),
			GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Head__Capless__Switch_opt3),
			GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Head__Capless__Switch_opt4),
			GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Head__Capless__Switch_opt5),
			GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Head__Capless__Switch_opt6),
			GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt1_Head__Capless__Switch_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, charity_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_Left_Hand_Open[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 1, 0, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, charity_Left_Hand_Open_Switch_Option_Left_Hand_Switch_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Left_Hand_Open_Switch_Option_Left_Hand_Switch_mesh_layer_4),
			GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_Left_Hand_Peace[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 1, 0, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, charity_Left_Hand_Peace_Switch_Option_Left_Hand_Peace_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Left_Hand_Peace_Switch_Option_Left_Hand_Peace_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_Left_Hand_Cap[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 1, 0, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, charity_Left_Hand_Switch_Option_Left_Hand_Cap_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Left_Hand_Switch_Option_Left_Hand_Cap_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_Left_Hand_Wing_Cap[] = {
	GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 1, 0, 0, 0, 0, 0),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_ALPHA, 60, 0, 0, charity_Left_Hand_Wing_Switch_Option_Left_Hand_Wing_Switch_mesh_layer_4),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_OPAQUE, charity_Left_Hand_Wing_Switch_Option_Left_Hand_Wing_Cap_mesh_layer_1),
			GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Left_Hand_Wing_Switch_Option_Left_Hand_Wing_Cap_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Head__Capless__Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Head__Capless__Switch_Option_Head__Capless__mesh_layer_1_mat_override_c_face1_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Head__Capless__Switch_Option_Head__Capless__mesh_layer_4_mat_override_c_face1_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Head__Capless__Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Head__Capless__Switch_Option_Head__Capless__mesh_layer_1_mat_override_c_face2_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Head__Capless__Switch_Option_Head__Capless__mesh_layer_4_mat_override_c_face2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Head__Capless__Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Head__Capless__Switch_Option_Head__Capless__mesh_layer_1_mat_override_c_face0_3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Head__Capless__Switch_Option_Head__Capless__mesh_layer_4_mat_override_c_face0_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Head__Capless__Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Head__Capless__Switch_Option_Head__Capless__mesh_layer_1_mat_override_c_face0_3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Head__Capless__Switch_Option_Head__Capless__mesh_layer_4_mat_override_c_face0_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Head__Capless__Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Head__Capless__Switch_Option_Head__Capless__mesh_layer_1_mat_override_c_face0_3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Head__Capless__Switch_Option_Head__Capless__mesh_layer_4_mat_override_c_face0_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Head__Capless__Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Head__Capless__Switch_Option_Head__Capless__mesh_layer_1_mat_override_c_face0_3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Head__Capless__Switch_Option_Head__Capless__mesh_layer_4_mat_override_c_face0_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Head__Capless__Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Head__Capless__Switch_Option_Head__Capless__mesh_layer_1_mat_override_c_face3_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Head__Capless__Switch_Option_Head__Capless__mesh_layer_4_mat_override_c_face3_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_jump_charity_Armature___Head__Capless_[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Head__Capless__Switch_Option_Head__Capless__mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Head__Capless__Switch_Option_Head__Capless__mesh_layer_4),
			GEO_CLOSE_NODE(),
			GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Head__Capless__Switch_opt1),
			GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Head__Capless__Switch_opt2),
			GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Head__Capless__Switch_opt3),
			GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Head__Capless__Switch_opt4),
			GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Head__Capless__Switch_opt5),
			GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Head__Capless__Switch_opt6),
			GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt1_Head__Capless__Switch_opt7),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_jump_charity_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, charity_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_4),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_jump_charity_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 1, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, charity_Left_Hand_Open_Switch_Option_Left_Hand_Switch_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Left_Hand_Open_Switch_Option_Left_Hand_Switch_mesh_layer_4),
				GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_jump_charity_Left_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 1, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, charity_Left_Hand_Peace_Switch_Option_Left_Hand_Peace_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Left_Hand_Peace_Switch_Option_Left_Hand_Peace_mesh_layer_4),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_jump_charity_Left_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 1, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, charity_Left_Hand_Switch_Option_Left_Hand_Cap_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Left_Hand_Switch_Option_Left_Hand_Cap_mesh_layer_4),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_jump_charity_Left_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 1, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, charity_Left_Hand_Wing_Switch_Option_Left_Hand_Wing_Switch_mesh_layer_4),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Left_Hand_Wing_Switch_Option_Left_Hand_Wing_Cap_mesh_layer_1),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Left_Hand_Wing_Switch_Option_Left_Hand_Wing_Cap_mesh_layer_4),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Head_DL_mesh_layer_1_mat_override_c_face1_1),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Head_DL_mesh_layer_4_mat_override_c_face1_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Head_DL_mesh_layer_1_mat_override_c_face2_2),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Head_DL_mesh_layer_4_mat_override_c_face2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Head_DL_mesh_layer_1_mat_override_c_face0_3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Head_DL_mesh_layer_4_mat_override_c_face0_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Head_DL_mesh_layer_1_mat_override_c_face0_3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Head_DL_mesh_layer_4_mat_override_c_face0_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Head_DL_mesh_layer_1_mat_override_c_face0_3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Head_DL_mesh_layer_4_mat_override_c_face0_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Head_DL_mesh_layer_1_mat_override_c_face0_3),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Head_DL_mesh_layer_4_mat_override_c_face0_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Head_DL_mesh_layer_1_mat_override_c_face3_4),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Head_DL_mesh_layer_4_mat_override_c_face3_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, charity_Butt_mesh_layer_1),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 41, -5, 0, charity_Torso_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Torso_mesh_layer_4),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 46, 5, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Head_DL_mesh_layer_1),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Head_DL_mesh_layer_4),
											GEO_CLOSE_NODE(),
											GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt1),
											GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt2),
											GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt3),
											GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt4),
											GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt5),
											GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt6),
											GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_Hatless_Switch_opt0_Eye_Material_Switch_opt7),
										GEO_CLOSE_NODE(),
										GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, -8, -63, 176),
										GEO_OPEN_NODE(),
											GEO_SCALE(LAYER_OPAQUE, 19005),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Left_Ball_DL_mesh_layer_4),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, -8, -63, -176),
										GEO_OPEN_NODE(),
											GEO_SCALE(LAYER_OPAQUE, 19005),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Right_Ball_DL_mesh_layer_4),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_jump_charity_Armature___Head__Capless_),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 120, -82, 126, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Left_Wing_DL_mesh_layer_4),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 120, -82, -126, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Right_Wing_DL_mesh_layer_4),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 14, -5, 44, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 2, 0, charity_Left_Arm_Color_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 50, 0, 0, charity_Left_Forearm_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 70, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Left_Hand_DL_mesh_layer_1),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Left_Hand_DL_mesh_layer_4),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_jump_charity_Right_Hand_Open),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 14, -5, -44, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 2, 0, charity_Right_Arm_Color_mesh_layer_1),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 50, 0, 0, charity_Right_Forearm_mesh_layer_1),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 70, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Right_Hand_DL_mesh_layer_1),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Right_Hand_DL_mesh_layer_4),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, 1, 0, 0, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_jump_charity_Left_Hand_Open),
										GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_jump_charity_Left_Hand_Peace),
										GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_jump_charity_Left_Hand_Cap),
										GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1_jump_charity_Left_Hand_Wing_Cap),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 10, -8, 32, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, -2, 0, charity_Left_Thigh_Color_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 78, 0, 0, charity_Left_Leg_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 64, 0, 0, charity_Left_Shoe_mesh_layer_1),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 10, -8, -32, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, -2, 0, charity_Right_Thigh_Color_mesh_layer_1),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 78, 0, 0, charity_Right_Leg_mesh_layer_1),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 64, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Right_Shoe_DL_mesh_layer_1),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2_jump_charity_Armature___Head__Capless_[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, charity_Head__Capless__Switch_Option_Head__Capless__mesh_layer_1_mat_override_Metal__METAL__0),
				GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Head__Capless__Switch_Option_Head__Capless__mesh_layer_4_mat_override_Metal__METAL__0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2_jump_charity_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, charity_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_4_mat_override_Metal__METAL__0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2_jump_charity_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 1, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, charity_Left_Hand_Open_Switch_Option_Left_Hand_Switch_mesh_layer_1_mat_override_Metal__METAL__0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Left_Hand_Open_Switch_Option_Left_Hand_Switch_mesh_layer_4_mat_override_Metal__METAL__0),
				GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2_jump_charity_Left_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 1, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, charity_Left_Hand_Peace_Switch_Option_Left_Hand_Peace_mesh_layer_1_mat_override_Metal__METAL__0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Left_Hand_Peace_Switch_Option_Left_Hand_Peace_mesh_layer_4_mat_override_Metal__METAL__0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2_jump_charity_Left_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 1, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 60, 0, 0, charity_Left_Hand_Switch_Option_Left_Hand_Cap_mesh_layer_1_mat_override_Metal__METAL__0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Left_Hand_Switch_Option_Left_Hand_Cap_mesh_layer_4_mat_override_Metal__METAL__0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2_jump_charity_Left_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 1, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_ALPHA, 60, 0, 0, charity_Left_Hand_Wing_Switch_Option_Left_Hand_Wing_Switch_mesh_layer_4_mat_override_Metal__METAL__0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_OPAQUE, charity_Left_Hand_Wing_Switch_Option_Left_Hand_Wing_Cap_mesh_layer_1_mat_override_Metal__METAL__0),
				GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Left_Hand_Wing_Switch_Option_Left_Hand_Wing_Cap_mesh_layer_4_mat_override_Metal__METAL__0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, charity_Butt_mesh_layer_1_mat_override_Metal__METAL__0),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 41, -5, 0, charity_Torso_mesh_layer_1_mat_override_Metal__METAL__0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Torso_mesh_layer_4_mat_override_Metal__METAL__0),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 46, 5, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_OPAQUE, charity_Head_DL_mesh_layer_1_mat_override_Metal__METAL__0),
												GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Head_DL_mesh_layer_4_mat_override_Metal__METAL__0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, -8, -63, 176),
										GEO_OPEN_NODE(),
											GEO_SCALE(LAYER_OPAQUE, 19005),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Left_Ball_DL_mesh_layer_4_mat_override_Metal__METAL__0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, -8, -63, -176),
										GEO_OPEN_NODE(),
											GEO_SCALE(LAYER_OPAQUE, 19005),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Right_Ball_DL_mesh_layer_4_mat_override_Metal__METAL__0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2_jump_charity_Armature___Head__Capless_),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 120, -82, 126, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Left_Wing_DL_mesh_layer_4_mat_override_Metal__METAL__0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 120, -82, -126, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Right_Wing_DL_mesh_layer_4_mat_override_Metal__METAL__0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 14, -5, 44, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 2, 0, charity_Left_Arm_Color_mesh_layer_1_mat_override_Metal__METAL__0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 50, 0, 0, charity_Left_Forearm_mesh_layer_1_mat_override_Metal__METAL__0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 70, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, charity_Left_Hand_DL_mesh_layer_1_mat_override_Metal__METAL__0),
													GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Left_Hand_DL_mesh_layer_4_mat_override_Metal__METAL__0),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2_jump_charity_Right_Hand_Open),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 14, -5, -44, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 2, 0, charity_Right_Arm_Color_mesh_layer_1_mat_override_Metal__METAL__0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 50, 0, 0, charity_Right_Forearm_mesh_layer_1_mat_override_Metal__METAL__0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 70, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_OPAQUE, charity_Right_Hand_DL_mesh_layer_1_mat_override_Metal__METAL__0),
													GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Right_Hand_DL_mesh_layer_4_mat_override_Metal__METAL__0),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, 1, 0, 0, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2_jump_charity_Left_Hand_Open),
										GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2_jump_charity_Left_Hand_Peace),
										GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2_jump_charity_Left_Hand_Cap),
										GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2_jump_charity_Left_Hand_Wing_Cap),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 10, -8, 32, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -2, 0, charity_Left_Thigh_Color_mesh_layer_1_mat_override_Metal__METAL__0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, charity_Left_Leg_mesh_layer_1_mat_override_Metal__METAL__0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 64, 0, 0, charity_Left_Shoe_mesh_layer_1_mat_override_Metal__METAL__0),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 10, -8, -32, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -2, 0, charity_Right_Thigh_Color_mesh_layer_1_mat_override_Metal__METAL__0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, charity_Right_Leg_mesh_layer_1_mat_override_Metal__METAL__0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 64, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_OPAQUE, charity_Right_Shoe_DL_mesh_layer_1_mat_override_Metal__METAL__0),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3_jump_charity_Armature___Head__Capless_[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
		GEO_OPEN_NODE(),
			GEO_NODE_START(),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Head__Capless__Switch_Option_Head__Capless__mesh_layer_1_mat_override_Metal__METAL__0),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Head__Capless__Switch_Option_Head__Capless__mesh_layer_4_mat_override_Metal__METAL__0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3_jump_charity_Right_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, charity_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_1_mat_override_Metal__METAL__0),
		GEO_OPEN_NODE(),
			GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Right_Hand_Open_Switch_Option_Right_Hand_Open_mesh_layer_4_mat_override_Metal__METAL__0),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3_jump_charity_Left_Hand_Open[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 1, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, charity_Left_Hand_Open_Switch_Option_Left_Hand_Switch_mesh_layer_1_mat_override_Metal__METAL__0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Left_Hand_Open_Switch_Option_Left_Hand_Switch_mesh_layer_4_mat_override_Metal__METAL__0),
				GEO_HELD_OBJECT(0, 0, 0, 0, geo_switch_mario_hand_grab_pos),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3_jump_charity_Left_Hand_Peace[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 1, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, charity_Left_Hand_Peace_Switch_Option_Left_Hand_Peace_mesh_layer_1_mat_override_Metal__METAL__0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Left_Hand_Peace_Switch_Option_Left_Hand_Peace_mesh_layer_4_mat_override_Metal__METAL__0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3_jump_charity_Left_Hand_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 1, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, charity_Left_Hand_Switch_Option_Left_Hand_Cap_mesh_layer_1_mat_override_Metal__METAL__0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Left_Hand_Switch_Option_Left_Hand_Cap_mesh_layer_4_mat_override_Metal__METAL__0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3_jump_charity_Left_Hand_Wing_Cap[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_TRANSLATE_ROTATE(LAYER_OPAQUE, 1, 0, 0, 0, 0, 0),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 60, 0, 0, charity_Left_Hand_Wing_Switch_Option_Left_Hand_Wing_Switch_mesh_layer_4_mat_override_Metal__METAL__0),
			GEO_OPEN_NODE(),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Left_Hand_Wing_Switch_Option_Left_Hand_Wing_Cap_mesh_layer_1_mat_override_Metal__METAL__0),
				GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Left_Hand_Wing_Switch_Option_Left_Hand_Wing_Cap_mesh_layer_4_mat_override_Metal__METAL__0),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
		GEO_OPEN_NODE(),
			GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 0, 0, charity_Butt_mesh_layer_1_mat_override_Metal__METAL__0),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_move_mario_part_from_parent),
				GEO_ASM(0, geo_mario_tilt_torso),
				GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 41, -5, 0, charity_Torso_mesh_layer_1_mat_override_Metal__METAL__0),
					GEO_OPEN_NODE(),
						GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Torso_mesh_layer_4_mat_override_Metal__METAL__0),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 46, 5, 0, NULL),
						GEO_OPEN_NODE(),
							GEO_ASM(0, geo_mario_head_rotation),
							GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
							GEO_OPEN_NODE(),
								GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
								GEO_OPEN_NODE(),
									GEO_NODE_START(),
									GEO_OPEN_NODE(),
										GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
										GEO_OPEN_NODE(),
											GEO_NODE_START(),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Head_DL_mesh_layer_1_mat_override_Metal__METAL__0),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Head_DL_mesh_layer_4_mat_override_Metal__METAL__0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, -8, -63, 176),
										GEO_OPEN_NODE(),
											GEO_SCALE(LAYER_OPAQUE, 19005),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Left_Ball_DL_mesh_layer_4_mat_override_Metal__METAL__0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, -8, -63, -176),
										GEO_OPEN_NODE(),
											GEO_SCALE(LAYER_OPAQUE, 19005),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Right_Ball_DL_mesh_layer_4_mat_override_Metal__METAL__0),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
									GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3_jump_charity_Armature___Head__Capless_),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 120, -82, 126, -15, 33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Left_Wing_DL_mesh_layer_4_mat_override_Metal__METAL__0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
								GEO_TRANSLATE_ROTATE(LAYER_FORCE, 120, -82, -126, 15, -33, -133),
								GEO_OPEN_NODE(),
									GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
									GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
									GEO_OPEN_NODE(),
										GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Right_Wing_DL_mesh_layer_4_mat_override_Metal__METAL__0),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 14, -5, 44, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 2, 0, charity_Left_Arm_Color_mesh_layer_1_mat_override_Metal__METAL__0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 50, 0, 0, charity_Left_Forearm_mesh_layer_1_mat_override_Metal__METAL__0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(1, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 70, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(1, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Left_Hand_DL_mesh_layer_1_mat_override_Metal__METAL__0),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Left_Hand_DL_mesh_layer_4_mat_override_Metal__METAL__0),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3_jump_charity_Right_Hand_Open),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
						GEO_ANIMATED_PART(LAYER_OPAQUE, 14, -5, -44, NULL),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, 2, 0, charity_Right_Arm_Color_mesh_layer_1_mat_override_Metal__METAL__0),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_TRANSPARENT, 50, 0, 0, charity_Right_Forearm_mesh_layer_1_mat_override_Metal__METAL__0),
								GEO_OPEN_NODE(),
									GEO_SWITCH_CASE(0, geo_switch_mario_hand),
									GEO_OPEN_NODE(),
										GEO_NODE_START(),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 70, 0, 0, NULL),
											GEO_OPEN_NODE(),
												GEO_ASM(0, geo_mario_hand_foot_scaler),
												GEO_SCALE(LAYER_FORCE, 65536),
												GEO_OPEN_NODE(),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Right_Hand_DL_mesh_layer_1_mat_override_Metal__METAL__0),
													GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Right_Hand_DL_mesh_layer_4_mat_override_Metal__METAL__0),
												GEO_CLOSE_NODE(),
												GEO_HELD_OBJECT(0, 1, 0, 0, geo_switch_mario_hand_grab_pos),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3_jump_charity_Left_Hand_Open),
										GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3_jump_charity_Left_Hand_Peace),
										GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3_jump_charity_Left_Hand_Cap),
										GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3_jump_charity_Left_Hand_Wing_Cap),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 10, -8, 32, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, -2, 0, charity_Left_Thigh_Color_mesh_layer_1_mat_override_Metal__METAL__0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 78, 0, 0, charity_Left_Leg_mesh_layer_1_mat_override_Metal__METAL__0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_TRANSPARENT, 64, 0, 0, charity_Left_Shoe_mesh_layer_1_mat_override_Metal__METAL__0),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ANIMATED_PART(LAYER_OPAQUE, 10, -8, -32, NULL),
				GEO_OPEN_NODE(),
					GEO_ANIMATED_PART(LAYER_TRANSPARENT, 0, -2, 0, charity_Right_Thigh_Color_mesh_layer_1_mat_override_Metal__METAL__0),
					GEO_OPEN_NODE(),
						GEO_ANIMATED_PART(LAYER_TRANSPARENT, 78, 0, 0, charity_Right_Leg_mesh_layer_1_mat_override_Metal__METAL__0),
						GEO_OPEN_NODE(),
							GEO_ANIMATED_PART(LAYER_OPAQUE, 64, 0, 0, NULL),
							GEO_OPEN_NODE(),
								GEO_ASM(2, geo_mario_hand_foot_scaler),
								GEO_SCALE(LAYER_FORCE, 65536),
								GEO_OPEN_NODE(),
									GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_Right_Shoe_DL_mesh_layer_1_mat_override_Metal__METAL__0),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt1[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, charity_Head_DL_mesh_layer_1_mat_override_c_face1_1),
		GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Head_DL_mesh_layer_4_mat_override_c_face1_1),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt2[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, charity_Head_DL_mesh_layer_1_mat_override_c_face2_2),
		GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Head_DL_mesh_layer_4_mat_override_c_face2_2),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt3[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, charity_Head_DL_mesh_layer_1_mat_override_c_face0_3),
		GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Head_DL_mesh_layer_4_mat_override_c_face0_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt4[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, charity_Head_DL_mesh_layer_1_mat_override_c_face0_3),
		GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Head_DL_mesh_layer_4_mat_override_c_face0_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt5[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, charity_Head_DL_mesh_layer_1_mat_override_c_face0_3),
		GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Head_DL_mesh_layer_4_mat_override_c_face0_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt6[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, charity_Head_DL_mesh_layer_1_mat_override_c_face0_3),
		GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Head_DL_mesh_layer_4_mat_override_c_face0_3),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt7[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, charity_Head_DL_mesh_layer_1_mat_override_c_face3_4),
		GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Head_DL_mesh_layer_4_mat_override_c_face3_4),
	GEO_CLOSE_NODE(),
	GEO_RETURN(),
};
const GeoLayout charity_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(1, 180, 100),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 19005),
			GEO_OPEN_NODE(),
				GEO_ASM(0, geo_mirror_mario_backface_culling),
				GEO_ASM(0, geo_mario_set_player_colors),
				GEO_ASM(0, geo_mirror_mario_set_alpha),
				GEO_SWITCH_CASE(0, geo_switch_mario_stand_run),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_SWITCH_CASE(0, geo_switch_mario_cap_effect),
						GEO_OPEN_NODE(),
							GEO_NODE_START(),
							GEO_OPEN_NODE(),
								GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, NULL),
								GEO_OPEN_NODE(),
									GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 0, 0, charity_Butt_mesh_layer_1),
									GEO_OPEN_NODE(),
										GEO_ASM(0, geo_move_mario_part_from_parent),
										GEO_ASM(0, geo_mario_tilt_torso),
										GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 41, -5, 0, charity_Torso_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Torso_mesh_layer_4),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 46, 5, 0, NULL),
												GEO_OPEN_NODE(),
													GEO_ASM(0, geo_mario_head_rotation),
													GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
													GEO_OPEN_NODE(),
														GEO_SWITCH_CASE(0, geo_switch_mario_cap_on_off),
														GEO_OPEN_NODE(),
															GEO_NODE_START(),
															GEO_OPEN_NODE(),
																GEO_SWITCH_CASE(0, geo_switch_mario_eyes),
																GEO_OPEN_NODE(),
																	GEO_NODE_START(),
																	GEO_OPEN_NODE(),
																		GEO_DISPLAY_LIST(LAYER_OPAQUE, charity_Head_DL_mesh_layer_1),
																		GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Head_DL_mesh_layer_4),
																	GEO_CLOSE_NODE(),
																	GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt1),
																	GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt2),
																	GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt3),
																	GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt4),
																	GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt5),
																	GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt6),
																	GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt0_Hatless_Switch_opt0_Eye_Material_Switch_opt7),
																GEO_CLOSE_NODE(),
																GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, -8, -63, 176),
																GEO_OPEN_NODE(),
																	GEO_SCALE(LAYER_OPAQUE, 19005),
																	GEO_OPEN_NODE(),
																		GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Left_Ball_DL_mesh_layer_4),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
																GEO_BILLBOARD_WITH_PARAMS(LAYER_OPAQUE, -8, -63, -176),
																GEO_OPEN_NODE(),
																	GEO_SCALE(LAYER_OPAQUE, 19005),
																	GEO_OPEN_NODE(),
																		GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Right_Ball_DL_mesh_layer_4),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
															GEO_CLOSE_NODE(),
															GEO_BRANCH(1, charity_Armature___Head__Capless_),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(LAYER_FORCE, 120, -82, 126, -15, 33, -133),
														GEO_OPEN_NODE(),
															GEO_ASM(1, geo_mario_rotate_wing_cap_wings),
															GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Left_Wing_DL_mesh_layer_4),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
														GEO_TRANSLATE_ROTATE(LAYER_FORCE, 120, -82, -126, 15, -33, -133),
														GEO_OPEN_NODE(),
															GEO_ASM(0, geo_mario_rotate_wing_cap_wings),
															GEO_ROTATION_NODE(LAYER_FORCE, 0, 0, 0),
															GEO_OPEN_NODE(),
																GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Right_Wing_DL_mesh_layer_4),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 14, -5, 44, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 2, 0, charity_Left_Arm_Color_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 50, 0, 0, charity_Left_Forearm_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_SWITCH_CASE(1, geo_switch_mario_hand),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(LAYER_OPAQUE, 70, 0, 0, NULL),
																	GEO_OPEN_NODE(),
																		GEO_ASM(1, geo_mario_hand_foot_scaler),
																		GEO_SCALE(LAYER_FORCE, 65536),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(LAYER_OPAQUE, charity_Left_Hand_DL_mesh_layer_1),
																			GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Left_Hand_DL_mesh_layer_4),
																		GEO_CLOSE_NODE(),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
																GEO_BRANCH(1, charity_Right_Hand_Open),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 14, -5, -44, NULL),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 0, 2, 0, charity_Right_Arm_Color_mesh_layer_1),
													GEO_OPEN_NODE(),
														GEO_ANIMATED_PART(LAYER_OPAQUE, 50, 0, 0, charity_Right_Forearm_mesh_layer_1),
														GEO_OPEN_NODE(),
															GEO_SWITCH_CASE(0, geo_switch_mario_hand),
															GEO_OPEN_NODE(),
																GEO_NODE_START(),
																GEO_OPEN_NODE(),
																	GEO_ANIMATED_PART(LAYER_OPAQUE, 70, 0, 0, NULL),
																	GEO_OPEN_NODE(),
																		GEO_ASM(0, geo_mario_hand_foot_scaler),
																		GEO_SCALE(LAYER_FORCE, 65536),
																		GEO_OPEN_NODE(),
																			GEO_DISPLAY_LIST(LAYER_OPAQUE, charity_Right_Hand_DL_mesh_layer_1),
																			GEO_DISPLAY_LIST(LAYER_ALPHA, charity_Right_Hand_DL_mesh_layer_4),
																		GEO_CLOSE_NODE(),
																		GEO_HELD_OBJECT(0, 1, 0, 0, geo_switch_mario_hand_grab_pos),
																	GEO_CLOSE_NODE(),
																GEO_CLOSE_NODE(),
																GEO_BRANCH(1, charity_Left_Hand_Open),
																GEO_BRANCH(1, charity_Left_Hand_Peace),
																GEO_BRANCH(1, charity_Left_Hand_Cap),
																GEO_BRANCH(1, charity_Left_Hand_Wing_Cap),
															GEO_CLOSE_NODE(),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 10, -8, 32, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -2, 0, charity_Left_Thigh_Color_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, charity_Left_Leg_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 64, 0, 0, charity_Left_Shoe_mesh_layer_1),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
										GEO_ANIMATED_PART(LAYER_OPAQUE, 10, -8, -32, NULL),
										GEO_OPEN_NODE(),
											GEO_ANIMATED_PART(LAYER_OPAQUE, 0, -2, 0, charity_Right_Thigh_Color_mesh_layer_1),
											GEO_OPEN_NODE(),
												GEO_ANIMATED_PART(LAYER_OPAQUE, 78, 0, 0, charity_Right_Leg_mesh_layer_1),
												GEO_OPEN_NODE(),
													GEO_ANIMATED_PART(LAYER_OPAQUE, 64, 0, 0, NULL),
													GEO_OPEN_NODE(),
														GEO_ASM(2, geo_mario_hand_foot_scaler),
														GEO_SCALE(LAYER_FORCE, 65536),
														GEO_OPEN_NODE(),
															GEO_DISPLAY_LIST(LAYER_OPAQUE, charity_Right_Shoe_DL_mesh_layer_1),
														GEO_CLOSE_NODE(),
													GEO_CLOSE_NODE(),
												GEO_CLOSE_NODE(),
											GEO_CLOSE_NODE(),
										GEO_CLOSE_NODE(),
									GEO_CLOSE_NODE(),
								GEO_CLOSE_NODE(),
							GEO_CLOSE_NODE(),
							GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt1),
							GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt2),
							GEO_BRANCH(1, charity_2_LoD_Switch_opt0_Cap_Effect_Switch_opt3),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ASM(1, geo_mirror_mario_backface_culling),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, charity_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, charity_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_TRANSPARENT, charity_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
