extern const GeoLayout cherry_wing_cap_Wing_Cap_Switch_opt1[];
extern const GeoLayout cherry_wing_cap_geo[];
extern Lights1 cherry_wing_cap_hat_lights;
extern u8 cherry_wing_cap_cherry_sweater_i8[];
extern u8 cherry_wing_cap_wing_2_ia8[];
extern u8 cherry_wing_cap_wing1_ia8[];
extern Vtx cherry_wing_cap_Wing_Cap_mesh_layer_1_vtx_0[87];
extern Gfx cherry_wing_cap_Wing_Cap_mesh_layer_1_tri_0[];
extern Vtx cherry_wing_cap_Wings_mesh_layer_4_vtx_0[8];
extern Gfx cherry_wing_cap_Wings_mesh_layer_4_tri_0[];
extern Vtx cherry_wing_cap_Wings_mesh_layer_4_vtx_1[8];
extern Gfx cherry_wing_cap_Wings_mesh_layer_4_tri_1[];
extern Gfx mat_cherry_wing_cap_hat[];
extern Gfx mat_revert_cherry_wing_cap_hat[];
extern Gfx mat_cherry_wing_cap_Wing_Tip[];
extern Gfx mat_revert_cherry_wing_cap_Wing_Tip[];
extern Gfx mat_cherry_wing_cap_Wing_Base[];
extern Gfx mat_revert_cherry_wing_cap_Wing_Base[];
extern Gfx cherry_wing_cap_Wing_Cap_mesh_layer_1[];
extern Gfx cherry_wing_cap_Wings_mesh_layer_4[];
extern Gfx cherry_wing_cap_material_revert_render_settings[];
