#include "src/game/envfx_snow.h"

const GeoLayout charity_cap_metal_wing_geo[] = {
	GEO_NODE_START(),
	GEO_OPEN_NODE(),
		GEO_SHADOW(0, 180, 75),
		GEO_OPEN_NODE(),
			GEO_SCALE(LAYER_FORCE, 16384),
			GEO_OPEN_NODE(),
				GEO_SWITCH_CASE(2, geo_switch_anim_state),
				GEO_OPEN_NODE(),
					GEO_NODE_START(),
					GEO_OPEN_NODE(),
						GEO_NODE_START(),
						GEO_OPEN_NODE(),
							GEO_DISPLAY_LIST(LAYER_OPAQUE, charity_cap_metal_wing_C_M_W__Cap_mesh_layer_1),
							GEO_DISPLAY_LIST(LAYER_ALPHA, charity_cap_metal_wing_C_M_W__Cap_mesh_layer_4),
							GEO_DISPLAY_LIST(LAYER_ALPHA, charity_cap_metal_wing_C_M_W__Wings_mesh_layer_4),
						GEO_CLOSE_NODE(),
					GEO_CLOSE_NODE(),
				GEO_CLOSE_NODE(),
				GEO_ASM(10, geo_update_layer_transparency),
			GEO_CLOSE_NODE(),
		GEO_CLOSE_NODE(),
		GEO_DISPLAY_LIST(LAYER_OPAQUE, charity_cap_metal_wing_material_revert_render_settings),
		GEO_DISPLAY_LIST(LAYER_ALPHA, charity_cap_metal_wing_material_revert_render_settings),
	GEO_CLOSE_NODE(),
	GEO_END(),
};
